server:
  port: 8030
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: provider_route
          uri: http://localhost:8181
          predicates:
            - Path=/provider/**
          filters:
            - StripPrefix=1
        - id: consumer_route
          uri: http://localhost:8010
          predicates:
            - Path=/consumer/**
          filters:
            - StripPrefix=1

