spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
  #    sentinel:
  #      transport:
  #        dashboard: localhost:8080
  #      filter:
  #        enabled: false
  application:
    name: pro
server:
  port: 8181
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#rocketmq:
#  name-server: 192.168.248.130:9876
#  producer:
#    group: myproducer